language: node_js
node_js:
  - "8.11.4"
env:
  - NODE_ENV=production
script:
  - cd client && npm install && npm install --only=dev --no-shrinkwrap && cd ..
  - npm install && npm install --only=dev --no-shrinkwrap
  - npm test
