dist: trusty
language: python
python:
  - "2.7"
node_js:
  - "8.9.1"
install:
  - pip install -r api/requirements/dev.txt
  - npm install
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
before_script:
  - python -c 'from api import server; server.app.run(port=8082)' &
script:
  - npm run test:server
  - npm run test:vue
  - xvfb-run npm run test:e2e-assuming-server-is-running
