dist: trusty
language: python
python:
  - "2.7"
node_js:
  - "8.9.1"
install:
  - pip install -r api/requirements/dev.txt
  - npm install
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
script:
  - npm run test:server
  - npm run test:unit
  - xvfb-run npm run test:e2e
