language: python
python:
  - "2.7"
node_js:
  - "8.9.1"
install:
  - pip install 'fabric<2.0'
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - npm install
env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest
script:
  - xvfb-run fab test
  - npm test