language: python
python:
  - "2.7"
node_js:
  - "8.9.1"
services:
  - postgresql
install:
  - pip install -r api/requirements/dev.txt
  - npm install
env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest
script:
  - npm run test:server
  - npm run test:unit
  - npm run test:e2e2
